SELECT
            T1.ASIGNADOA,
            T1.ITIQUETE,
			REPLACE(CAST(AVG(T1.QMINATENCIONEMPRESA)/60.00 AS VARCHAR(20)),'.',',') AS PROMEDIOATENCION,
			CASE
			WHEN AVG(T1.QMINATENCIONEMPRESA)/60.00 <=5 THEN 'En Objetivo'
			ELSE 'Fuera de Objetivo'
			END AS OBJETIVOTA,
			REPLACE(CAST(AVG(T1.QMINSOLUCIONEMPRESA)/60.00 AS VARCHAR(20)),'.',',') AS PROMEDIOSOLUCION,
			CASE
			WHEN AVG(T1.QMINSOLUCIONEMPRESA)/60.00 <=18 THEN 'En Objetivo'
			ELSE 'Fuera de Objetivo'
			END AS OBJETIVOTS
	        FROM SOP_TIQUETES T1
	        LEFT JOIN ABADTIT T7 ON T7.ITABLA = 'ESTADOAPERTURA' AND T1.ITDESTADOAPERTURA = T7.ITITULO
	        LEFT JOIN ABADTIT T6 ON T6.ITABLA = 'ITDSOLICITUDC' AND T1.ITDSOLICITUD = T6.ITITULO
	        WHERE
            T1.BANULADO = 'F'
            AND EXTRACT(MONTH FROM T1.FHCIERRE) = :MES
            AND EXTRACT(YEAR FROM T1.FHCIERRE) = :ANIO
            AND T1.ASIGNADOA IN ('SALARCON', 'ACESPEDES', 'ATORO', 'AGIL', 'TLEON', 'VRESTREPO')
            AND T1.ITEMA IN ('AT-APO75', 'AT-CAP55', 'P-NP', 'AT-APO100', 'AT-APO105', 'AT-APO25', 'AT-APO45', 'AT-APO60', 'AT-APO95', 'AT-APO70', 'AT-APO65', 'AT-APO05', 'AT-APO35', 'AT-APO80', 'AT-APO90', 'AT-APO15', 'AT-APO40', 'AT-APO30', 'AT-APO50', 'AT-APO20', 'AT-APO120', 'AT-APO55', 'AT-APO85', 'AT-APO10')
            AND T7.NTITULO IN('','1 - Atención sin novedades', '1 - Cliente no contesta', '1 - En pausa por el asesor', '1 - En pausa por el cliente', '1 - Escalado a AT', '1 - Escalado a Ing')
            AND T6.NTITULO IN ('','1 - Consulta', '1 - Envío instructivo (con asistencia)', '1 - Falta de capacitación', '1 - Falta de recurso', '1 - ING Servicios otros', '1 - ING Servicios rep. BD', '1 - ING Servicios SQL', '1 - Intermitencia servidores InSoft', '1 - Novedad de configuración', '1 - PQR - Caso reasignado a otro Ingeniero', '1 - PQR - Error del sistema', '1 - PQR - Error del sistema (causa no identificada)', '1 - PQR - Error por cambio anterior (para uso AT e ING únicamente)', '1 - PQR - Error por caso nuevo (para uso AT e ING únicamente)', '1 - PQR - Error por normativa (para uso AT e ING únicamente)')
        	--AND T1.ITIQUETE NOT IN (1094695,1095002,1090419,1109577,1111844,1058040,1114476,1085483,1109712,1108677,1106529,1107956) -- SE VAN A IR SACANDO DEL CÁLCULO LOS TKS QUE POR ALGUNA RAZÓN NO SERÁN CONTADOS PARA TIEMPOS
            AND T1.ITIQUETEBASE IS NULL
            AND T1.ASIGNADOA<>T1.ABIERTOPOR
            AND T1.BEXCLUIRINFORMES IS NULL
            AND T1.FHSOLUCIONADO IS DISTINCT FROM T1.FHCIERRE
            AND T1.ITIQUETE=1179814
       		GROUP BY T1.ASIGNADOA,T1.ITIQUETE           
		
-- Oportunidad de mejoras (basado en cierre TKs de Ing)	

--GROUP BY QyANIO_CIERRE,MES_TRIMESTRE

		
--Para análisis de pólizas
--1
SELECT ITERCERO,MAX(FFINPOLIZA) 
FROM MOVSOLICITUDPOLIZAS
WHERE IESTADO>0 AND BFACTURA='T' AND FINICIOPOLIZA BETWEEN '2024-01-01' AND LOCALTIMESTAMP
GROUP BY ITERCERO
HAVING MAX(FFINPOLIZA)>=LOCALTIMESTAMP 

--2
SELECT *
FROM MOVSOLICITUDPOLIZAS
WHERE ITERCERO='8371' AND IESTADO>0 AND BFACTURA='T'
--Fin pólizas


--TKs ZeroTier
SELECT ITIQUETE
FROM SOP_TIQUETES
WHERE 
ICLASIFICADOR='ING14' 
AND ITEMA='ING'
AND FHSOLUCIONADO>'2025-06-05' --fecha de última revisión
--





--Dedicación histórica promedio de TKs F1 por especialista
SELECT ASIGNADOA
,CASE 
	WHEN ITEMA='AT-PRU11' THEN 'Fase 1'
	WHEN ITEMA='AT-PRU00' THEN 'Fase 3'
	WHEN ITEMA='AT-PRU20' THEN 'Fase 4'
END AS FASE
,COUNT(*)
,AVG(QDEDICACION) AS Dedicacion_minutos
FROM SOP_TIQUETES
WHERE ITEMA IN ('AT-PRU11','AT-PRU00','AT-PRU20') AND ASIGNADOA IN ('ATORO','ACESPEDES','AGIL','TLEON','VRESTREPO','SALARCON')
GROUP BY ASIGNADOA,ITEMA
--



--Estado General TKs Analistas
SELECT 
T1.ASIGNADOA
,COUNT (CASE WHEN T1.FHCIERRE IS NULL AND T1.FHSOLUCIONADO IS NULL AND T1.FHATENDIDO IS NULL THEN 1 END) Q_TKS_SIN_ATENDER
,COUNT (CASE WHEN T1.FHCIERRE IS NULL AND T1.FHSOLUCIONADO IS NULL AND T1.FHATENDIDO IS DISTINCT FROM NULL THEN 1 END) Q_TKS_ATENDIDOS_SIN_SOLUCIONAR
,COUNT (CASE WHEN T1.FHCIERRE IS NULL AND T1.FHSOLUCIONADO IS DISTINCT FROM NULL THEN 1 END) AS Q_TKS_SOLUCIONADOS_SIN_CERRAR
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE 
T1.BANULADO='F'
AND T1.ASIGNADOA IN ('EDUQUE','SCALLE','JCASTILLO')
AND (T2.NTEMA LIKE '%Premium%' OR T2.NTEMA LIKE '%Sop AT%')
AND T1.FHAPERTURA>='2025-07-01'
GROUP BY T1.ASIGNADOA

--TKs sin atender Analistas
WITH X1 AS 
(
SELECT T1.ITIQUETE
,T2.NTEMA
,T1.ASUNTO
,T4.NTITULO AS ESTADO
,T1.ASIGNADOA
,T1.FHAPERTURA
,TRIM(CASE 
	WHEN T1.BANULADO='T' THEN 'TK Anulado' 
WHEN T1.FHCIERRE IS NOT NULL THEN 'TK Cerrado' 
WHEN T1.FHSOLUCIONADO IS NOT NULL THEN 'TK Solucionado'
WHEN T1.FHATENDIDO IS NOT NULL THEN 'TK Atendido'
WHEN T1.FHATENDIDO IS NULL THEN 'TK Sin Atender'
ELSE 'Error Revisar SQL'
END) AS EstadoTiquete
,MIN(CAST((LOCALTIMESTAMP - T3.FHMENSAJE) AS DECIMAL (10,2))) AS DIAS_DESDE_CREACION
,CASE 
	WHEN T1.ITIQUETE=1282138 THEN 'PRUEBA'
END AS OBSERVACIONES
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
LEFT JOIN SOP_MENSAJES T3 ON T1.ITIQUETE=T3.ITIQUETE
LEFT JOIN ABADTIT T4 ON T4.ITABLA='ESTADOAPERTURA' AND T1.ITDESTADOAPERTURA=T4.ITITULO
WHERE 
T1.ASIGNADOA IN ('SCALLE','JCASTILLO','EDUQUE') 
AND T1.FHSOLUCIONADO IS NULL AND T1.BANULADO='F'
AND T2.NTEMA NOT LIKE '%Pruebas%'
GROUP BY T1.ITIQUETE, T2.NTEMA, T1.ASUNTO, T4.NTITULO, T1.ASIGNADOA, T1.FHAPERTURA,T1.BANULADO
,TRIM(CASE 
WHEN T1.BANULADO='T' THEN 'TK Anulado' 
WHEN T1.FHCIERRE IS NOT NULL THEN 'TK Cerrado' 
WHEN T1.FHSOLUCIONADO IS NOT NULL THEN 'TK Solucionado'
WHEN T1.FHATENDIDO IS NOT NULL THEN 'TK Atendido'
WHEN T1.FHATENDIDO IS NULL THEN 'TK Sin Atender'
ELSE 'Error Revisar SQL'
END)
,CASE 
WHEN T1.ITIQUETE=1282138 THEN 'PRUEBA'
END
)
SELECT ITIQUETE,NTEMA,ASUNTO,ESTADO,ASIGNADOA,FHAPERTURA,EstadoTiquete,DIAS_DESDE_CREACION,OBSERVACIONES
FROM X1
WHERE EstadoTiquete IN ('TK Sin Atender')
--GROUP BY ITIQUETE,NTEMA,ASUNTO,ESTADO,ASIGNADOA,FHAPERTURA,EstadoTiquete,OBSERVACIONES,DIAS_DESDE_CREACION
ORDER BY ASIGNADOA,NTEMA, DIAS_DESDE_CREACION desc

--TKs sin atender ni solucionar Analistas (para excel control)
SELECT *
FROM(
SELECT ITIQUETE,NTEMA,ASUNTO,ESTADO,ASIGNADOA,FHAPERTURA,EstadoTiquete, MIN(DIAS_DESDE_ULTIMO_MENSAJE) AS DIAS_DESDE_ULTIMO_MENSAJE ,TIPO_SOLICITUD_APERTURA,OBSERVACIONES
FROM(
SELECT T1.ITIQUETE
,T2.NTEMA	
,T1.ASUNTO
,T4.NTITULO AS ESTADO
,T1.ASIGNADOA
,T1.FHAPERTURA
,TRIM(CASE 
WHEN T1.BANULADO='T' THEN 'TK Anulado' 
WHEN T1.FHCIERRE IS NOT NULL THEN 'TK Cerrado' 
WHEN T1.FHSOLUCIONADO IS NOT NULL THEN 'TK Solucionado'
WHEN T1.FHATENDIDO IS NOT NULL THEN 'TK Atendido'
WHEN T1.FHATENDIDO IS NULL THEN 'TK Sin Atender'
ELSE 'Error Revisar SQL'
END) AS EstadoTiquete
,REPLACE(CAST((LOCALTIMESTAMP - T3.FHMENSAJE) AS DECIMAL (10,2)),'.',',') AS DIAS_DESDE_ULTIMO_MENSAJE
,T6.NTITULO AS TIPO_SOLICITUD_APERTURA
,CASE WHEN LOWER(T1.ASUNTO) LIKE '%mejora%'OR T6.NTITULO LIKE '%mejora%' THEN 'Mejora' END AS OBSERVACIONES
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
LEFT JOIN SOP_MENSAJES T3 ON T1.ITIQUETE=T3.ITIQUETE
LEFT JOIN ABADTIT T4 ON T4.ITABLA='ESTADOAPERTURA' AND T1.ITDESTADOAPERTURA=T4.ITITULO
LEFT JOIN ABADTIT T6 ON T6.ITABLA='ITDSOLICITUD' AND T1.ITDSOLICITUDA=T6.ITITULO
WHERE 
T1.ASIGNADOA IN ('SCALLE','JCASTILLO','EDUQUE') 
AND T1.FHSOLUCIONADO IS NULL AND T1.BANULADO='F'
AND T2.NTEMA NOT LIKE '%Prueba%'
)
WHERE EstadoTiquete IN ('TK Atendido')
GROUP BY ITIQUETE,NTEMA,ASIGNADOA,FHAPERTURA,EstadoTiquete,OBSERVACIONES,ESTADO,ASUNTO,TIPO_SOLICITUD_APERTURA
UNION
SELECT ITIQUETE,NTEMA,ASUNTO,ESTADO,ASIGNADOA,FHAPERTURA,EstadoTiquete, MIN(DIAS_DESDE_ULTIMO_MENSAJE) AS DIAS_ULTIMO_MENSAJE,TIPO_SOLICITUD_APERTURA,OBSERVACIONES
FROM(
SELECT T1.ITIQUETE
,T2.NTEMA
,T1.ASUNTO
,T4.NTITULO AS ESTADO
,T1.ASIGNADOA
,T1.FHAPERTURA
,TRIM(CASE 
	WHEN T1.BANULADO='T' THEN 'TK Anulado' 
WHEN T1.FHCIERRE IS NOT NULL THEN 'TK Cerrado' 
WHEN T1.FHSOLUCIONADO IS NOT NULL THEN 'TK Solucionado'
WHEN T1.FHATENDIDO IS NOT NULL THEN 'TK Atendido'
WHEN T1.FHATENDIDO IS NULL THEN 'TK Sin Atender'
ELSE 'Error Revisar SQL'
END) AS EstadoTiquete
,REPLACE(CAST((LOCALTIMESTAMP - T3.FHMENSAJE) AS DECIMAL (10,2)),'.',',') AS DIAS_DESDE_ULTIMO_MENSAJE
,T6.NTITULO AS TIPO_SOLICITUD_APERTURA
,CASE WHEN LOWER(T1.ASUNTO) LIKE '%mejora%' OR T6.NTITULO LIKE '%mejora%'THEN 'Mejora' END AS OBSERVACIONES
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
LEFT JOIN SOP_MENSAJES T3 ON T1.ITIQUETE=T3.ITIQUETE
LEFT JOIN ABADTIT T4 ON T4.ITABLA='ESTADOAPERTURA' AND T1.ITDESTADOAPERTURA=T4.ITITULO
LEFT JOIN ABADTIT T6 ON T6.ITABLA='ITDSOLICITUD' AND T1.ITDSOLICITUDA=T6.ITITULO
WHERE 
T1.ASIGNADOA IN ('SCALLE','JCASTILLO','EDUQUE') 
AND T1.FHSOLUCIONADO IS NULL AND T1.BANULADO='F'
AND T2.NTEMA NOT LIKE '%Pruebas%'
)
WHERE EstadoTiquete IN ('TK Sin Atender')
GROUP BY ITIQUETE,NTEMA,ASIGNADOA,FHAPERTURA,EstadoTiquete,OBSERVACIONES,ESTADO,ASUNTO,TIPO_SOLICITUD_APERTURA
)
ORDER BY ASIGNADOA,OBSERVACIONES,ESTADOTIQUETE DESC,DIAS_DESDE_ULTIMO_MENSAJE DESC

--DEMANDA ANALISTA DIA (POR SOP AT Y PREMIUM)
WITH X1 AS
(
SELECT CAST(T1.FHAPERTURA AS DATE) AS FHAPERTURA,T2.NTEMA,T1.ASIGNADOA,T2.NCATEGORIA
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE 
T2.NCATEGORIA IN ('AT - Apoyo','DIS - Soporte Premium') 
AND T1.FHAPERTURA >='2025-07-02' 
AND (T2.NTEMA LIKE '%Sop AT%' OR T2.NTEMA LIKE '%Asesoría%' OR T2.NTEMA LIKE '%Premium%')
AND T1.ASIGNADOA IN ('EDUQUE','SCALLE','JCASTILLO')
)
SELECT 
ASIGNADOA AS ANALISTA
,FHAPERTURA AS FECHA_APERTURA
,COUNT(NTEMA) AS DEMANDA_TOTAL
,COUNT(CASE WHEN NCATEGORIA='AT - Apoyo' THEN 1 END) AS DEMANDA_ANALISTA
,COUNT(CASE WHEN NCATEGORIA='DIS - Soporte Premium' THEN 1 END) DEMANDA_DIS_PREMIUM
,(COUNT(CASE WHEN NCATEGORIA='AT - Apoyo' THEN 1 END)/CAST(COUNT(NTEMA) AS DECIMAL(10,2))*100)||'%' PORCENTAJE_ANALISTA
,(COUNT(CASE WHEN NCATEGORIA='DIS - Soporte Premium' THEN 1 END)/CAST(COUNT(NTEMA) AS DECIMAL(10,2))*100)||'%' PORCENTAJE_DIS_PREMIUM
FROM X1
GROUP BY ASIGNADOA,FHAPERTURA
ORDER BY ASIGNADOA,FHAPERTURA

--DEMANDA ANALISTA MES (POR SOP AT Y PREMIUM)
WITH X1 AS
(
SELECT 
EXTRACT(YEAR FROM T1.FHAPERTURA) AS ANIO_APERTURA
,EXTRACT(MONTH FROM T1.FHAPERTURA) AS MES_APERTURA
,T2.NTEMA
,T1.ASIGNADOA
,T2.NCATEGORIA
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE 
T2.NCATEGORIA IN ('AT - Apoyo','DIS - Soporte Premium') 
AND T1.FHAPERTURA >='2025-07-02' 
AND (T2.NTEMA LIKE '%Sop AT%' OR T2.NTEMA LIKE '%Asesoría%' OR T2.NTEMA LIKE '%Premium%')
AND T1.ASIGNADOA IN ('EDUQUE','SCALLE','JCASTILLO')
)
SELECT 
ANIO_APERTURA||'/'||MES_APERTURA AS ANIO_MES_APERTURA
,ASIGNADOA AS ANALISTA
,COUNT(NTEMA) AS DEMANDA_TOTAL
,COUNT(CASE WHEN NCATEGORIA='AT - Apoyo' THEN 1 END) AS DEMANDA_ANALISTA
,COUNT(CASE WHEN NCATEGORIA='DIS - Soporte Premium' THEN 1 END) DEMANDA_DIS_PREMIUM
,(COUNT(CASE WHEN NCATEGORIA='AT - Apoyo' THEN 1 END)/CAST(COUNT(NTEMA) AS DECIMAL(10,2))*100)||'%' PORCENTAJE_ANALISTA
,(COUNT(CASE WHEN NCATEGORIA='DIS - Soporte Premium' THEN 1 END)/CAST(COUNT(NTEMA) AS DECIMAL(10,2))*100)||'%' PORCENTAJE_DIS_PREMIUM
FROM X1
GROUP BY ASIGNADOA,ANIO_APERTURA,MES_APERTURA
ORDER BY ASIGNADOA,ANIO_APERTURA||'/'||MES_APERTURA

--Tiempos Analistas Distribuidores Premium
SELECT  *
FROM PROC_TIEMPOSET('QADIS',:MESSOLUCION,:ANIOSOLUCION)

--Tiempos Analistas Sop AT
SELECT  *
FROM PROC_TIEMPOSET('QASOPAT',:MESSOLUCION,:ANIOSOLUCION)

--Promedio dedicación en Hr por tema y Analista
SELECT *
FROM(
SELECT T2.NTEMA,T1.ASIGNADOA,COUNT(*) AS CANTIDAD,AVG(T1.QDEDICACION)/60.00 AS DEDICACION_Hr
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE 
T1.ASIGNADOA IN ('EDUQUE','SCALLE','JCASTILLO')
AND T1.BANULADO='F'
AND T1.FHAPERTURA>='2025-07-01'
AND (T2.NTEMA LIKE '%Premium%' OR T2.NTEMA LIKE '%Sop AT%')
AND T1.FHSOLUCIONADO IS DISTINCT FROM NULL
GROUP BY T2.NTEMA,T1.ASIGNADOA
)
ORDER BY DEDICACION_Hr DESC

--Seguimiento documentación TKs pruebas de Analistas
SELECT T1.ITIQUETE,T1.ASIGNADOA,T2.NTEMA
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE 
T2.NTEMA LIKE '%Pruebas%' 
AND T1.FHSOLUCIONADO IS DISTINCT FROM NULL
AND T1.ASIGNADOA IN ('SCALLE','EDUQUE','JCASTILLO')
AND T1.FHSOLUCIONADO>='2025-07-11' --FECHA ÚLTIMO SEGUIMIENTO
ORDER BY T1.ASIGNADOA


--Promedio de demanda por día y por tema SOP AT(histórico)
WITH X1 AS(
SELECT CAST(T1.FHAPERTURA AS DATE) AS FHAPERTURA,EXTRACT(WEEKDAY FROM T1.FHAPERTURA) AS DIA_SEMANA,T2.NTEMA AS NTEMA
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE T2.NTEMA LIKE '%Sop AT%'
AND T1.FHAPERTURA>='2024-01-01'
GROUP BY T1.FHAPERTURA,T2.NTEMA
ORDER BY T1.FHAPERTURA DESC
),
X2 AS(
SELECT FHAPERTURA,DIA_SEMANA,NTEMA,COUNT(FHAPERTURA) AS CUENTA
FROM X1
GROUP BY FHAPERTURA,NTEMA,DIA_SEMANA
ORDER BY FHAPERTURA DESC
)
SELECT 
NTEMA,
CASE 
  WHEN DIA_SEMANA=1 THEN 'Lunes'
  WHEN DIA_SEMANA=2 THEN 'Martes'
  WHEN DIA_SEMANA=3 THEN 'Miércoles'
  WHEN DIA_SEMANA=4 THEN 'Jueves'
  WHEN DIA_SEMANA=5 THEN 'Viernes'
  WHEN DIA_SEMANA=6 THEN 'Sábado'
  WHEN DIA_SEMANA=7 THEN 'Domingo'
  ELSE 'Desconocido'
END AS DIA
,AVG(CUENTA)
FROM X2
GROUP BY NTEMA,DIA_SEMANA

--Promedio de demanda por día y por tema DIS PREMIUM (histórico)
WITH X1 AS(
SELECT CAST(T1.FHAPERTURA AS DATE) AS FHAPERTURA,EXTRACT(WEEKDAY FROM T1.FHAPERTURA) AS DIA_SEMANA,T2.NTEMA AS NTEMA
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE T2.NTEMA LIKE '%Premium%'
AND T1.FHAPERTURA>='2024-01-01'
GROUP BY T1.FHAPERTURA,T2.NTEMA
ORDER BY T1.FHAPERTURA DESC
),
X2 AS(
SELECT FHAPERTURA,DIA_SEMANA,NTEMA,COUNT(FHAPERTURA) AS CUENTA
FROM X1
GROUP BY FHAPERTURA,NTEMA,DIA_SEMANA
ORDER BY FHAPERTURA DESC
)
SELECT 
NTEMA,
CASE 
  WHEN DIA_SEMANA=1 THEN 'Lunes'
  WHEN DIA_SEMANA=2 THEN 'Martes'
  WHEN DIA_SEMANA=3 THEN 'Miércoles'
  WHEN DIA_SEMANA=4 THEN 'Jueves'
  WHEN DIA_SEMANA=5 THEN 'Viernes'
  WHEN DIA_SEMANA=6 THEN 'Sábado'
  WHEN DIA_SEMANA=7 THEN 'Domingo'
  ELSE 'Desconocido'
END AS DIA
,AVG(CUENTA)
FROM X2
--WHERE DIA_SEMANA=6
GROUP BY NTEMA,DIA_SEMANA

--Demanda temporal COSTOS SOPORTE SCALLE
WITH X1 AS 
(
SELECT T1.ITIQUETE
,T2.NTEMA
,T1.ASUNTO
,T4.NTITULO AS ESTADO
,T1.ASIGNADOA
,T1.FHAPERTURA
,TRIM(CASE 
	WHEN T1.BANULADO='T' THEN 'TK Anulado' 
WHEN T1.FHCIERRE IS NOT NULL THEN 'TK Cerrado' 
WHEN T1.FHSOLUCIONADO IS NOT NULL THEN 'TK Solucionado'
WHEN T1.FHATENDIDO IS NOT NULL THEN 'TK Atendido'
WHEN T1.FHATENDIDO IS NULL THEN 'TK Sin Atender'
ELSE 'Error Revisar SQL'
END) AS EstadoTiquete
,MIN(CAST((LOCALTIMESTAMP - T3.FHMENSAJE) AS DECIMAL (10,2))) AS DIAS_DESDE_CREACION
,CASE 
	WHEN T1.ITIQUETE=1282138 THEN 'PRUEBA'
END AS OBSERVACIONES
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
LEFT JOIN SOP_MENSAJES T3 ON T1.ITIQUETE=T3.ITIQUETE
LEFT JOIN ABADTIT T4 ON T4.ITABLA='ESTADOAPERTURA' AND T1.ITDESTADOAPERTURA=T4.ITITULO
WHERE 
T1.ASIGNADOA IN ('SCALLE') 
AND T1.FHSOLUCIONADO IS NULL AND T1.BANULADO='F'
AND T1.ITEMA IN ('COP','SDCOS')
GROUP BY T1.ITIQUETE, T2.NTEMA, T1.ASUNTO, T4.NTITULO, T1.ASIGNADOA, T1.FHAPERTURA,T1.BANULADO
,TRIM(CASE 
WHEN T1.BANULADO='T' THEN 'TK Anulado' 
WHEN T1.FHCIERRE IS NOT NULL THEN 'TK Cerrado' 
WHEN T1.FHSOLUCIONADO IS NOT NULL THEN 'TK Solucionado'
WHEN T1.FHATENDIDO IS NOT NULL THEN 'TK Atendido'
WHEN T1.FHATENDIDO IS NULL THEN 'TK Sin Atender'
ELSE 'Error Revisar SQL'
END)
,CASE 
WHEN T1.ITIQUETE=1282138 THEN 'PRUEBA'
END
)
SELECT ITIQUETE,NTEMA,ASUNTO,ESTADO,ASIGNADOA,FHAPERTURA,EstadoTiquete,DIAS_DESDE_CREACION,OBSERVACIONES
FROM X1
WHERE EstadoTiquete IN ('TK Sin Atender')
--GROUP BY ITIQUETE,NTEMA,ASUNTO,ESTADO,ASIGNADOA,FHAPERTURA,EstadoTiquete,OBSERVACIONES,DIAS_DESDE_CREACION
ORDER BY ASIGNADOA,NTEMA, DIAS_DESDE_CREACION desc


WITH X1 AS(
SELECT CAST(T1.FHAPERTURA AS DATE) AS FHAPERTURA,EXTRACT(WEEKDAY FROM T1.FHAPERTURA) AS DIA_SEMANA,T2.NTEMA AS NTEMA
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE T2.NTEMA LIKE '%Sop AT%'
AND T1.FHAPERTURA>='2024-01-01'
GROUP BY T1.FHAPERTURA,T2.NTEMA
ORDER BY T1.FHAPERTURA DESC
)
SELECT FHAPERTURA,NTEMA,COUNT(FHAPERTURA) AS CUENTA
FROM X1
GROUP BY FHAPERTURA,NTEMA
ORDER BY FHAPERTURA DESC




SELECT B.NTEMA
FROM SOP_PERFILESPORTEMA A
LEFT JOIN SOP_TEMAS B ON A.ITEMA=B.ITEMA
WHERE IPERFIL='INS_CALP_A03'


WITH X1 AS(
SELECT CAST(T1.FHAPERTURA AS DATE) AS FHAPERTURA,EXTRACT(WEEKDAY FROM T1.FHAPERTURA) AS DIA_SEMANA,T2.NTEMA AS NTEMA
FROM SOP_TIQUETES T1
LEFT JOIN SOP_TEMAS T2 ON T1.ITEMA=T2.ITEMA
WHERE T2.NTEMA LIKE '%Premium%'
AND T1.FHAPERTURA>='2024-01-01'
GROUP BY T1.FHAPERTURA,T2.NTEMA
ORDER BY T1.FHAPERTURA DESC
)
SELECT FHAPERTURA,DIA_SEMANA,NTEMA,COUNT(FHAPERTURA) AS CUENTA
FROM X1
WHERE DIA_SEMANA IN :DIA_SEMANA
GROUP BY FHAPERTURA,NTEMA,DIA_SEMANA
ORDER BY FHAPERTURA DESC



WITH X1 AS (
SELECT T2.ITERCERO AS ITERCERO,T1.ITDOPER, MAX(T1.QPROMEDIO) AS MAXIMO
FROM REGINISIS_PROMOPR T1
LEFT JOIN REGINISIS_GENERAL T2 ON T1.IREGISTRO=T2.IREGISTRO
LEFT JOIN TERCEROS T3 ON T2.ITERCERO=T3.ITERCERO
WHERE T1.ITDOPER IN ('PLA8','PLN1','PLN2') AND T2.ITERCERO IS NOT NULL AND T1.QPROMEDIO>0 --AND T3.ICIUDAD=001 AND T3.IDEPARTAMENTO=17
GROUP BY T2.ITERCERO,T1.ITDOPER)
SELECT DISTINCT ITERCERO
FROM X1
WHERE EXISTS(SELECT 1
			FROM MOVSOLICITUDPOLIZAS TX
			WHERE (TX.IAUTORIZACION = 1)
			AND (TX.FFINPOLIZA >= LOCALTIMESTAMP)
			AND TX.ITERCERO=ITERCERO
			GROUP BY TX.ITERCERO,TX.IPOLIZA
			HAVING SUM(TX.IESTADO) > 0	
			)


			


